# Generated by Django 4.1.7 on 2023-03-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unisssApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
    ]
